### ISSUE TITLE
Vypracovaný projekt půjčovna(carhire) k lekci č. 10

### ISSUE THREAD

**Issue by RenataTuronova** [RenataTuronova/python-012021#10]
@andywaltlova 

Ahoj Andy,

nahrála jsem upravený projekt Půjčovna podle zadání k lekci č. 10. Prosím o kontrolu.

Děkuji a přeji hezký den :)

**Comment by andywaltlova** [comment]
### 46 ✔️ 
- Super, přesně tak ja kto máš. nejvíce se hodí přidat obě vazby k samotné výpujčce 👍 
### 47 ✔️ 
- Peknee i s bonusem, akorat tedy nevim jestli si nezapomela pushnout novou verzi databaze, ja jsem si nejdriv musela udelat migrace aby mi fungoval hirelist - asi nejaka zmena v nazvech atributu u modelu `Hire`
- template je moc pekna, super ze vyuzivas i odkaz na auto a zakaznika :)
### 48 ✔️ 
- Tabulka super, pekne ze zobrazujes jenom dny a ne cely casovy rozdil :)
### 49 ✔️ 
- Super, funguje jak ma 👍 
### 50 ✔️ 
- Propojene to mas take moc pekne - ulehcilo mi to opravovani :-)

---
Tyden 10 tedy hotovy 🥳  Bodu mas 50, chybi vlastne jen 11 lekce - kdyz ji budes chtit opravit klidne mi sem muzes hodit zase issue, nevadi ze uz je po kurzu :)
