### ISSUE TITLE
Hotové úkoly lekce č.2

### ISSUE THREAD

**Issue by RenataTuronova** [RenataTuronova/python-012021#2]
@andywaltlova  

Ahoj Andy, 

nahrála jsem úkoly z druhé lekce, zatím mám hotové příklady č. 6 - 8. Mohla bys mi je prosím zkontrolovat? Děkuji :-)

Ještě mám otázku u příkladu č. 8. ohledně kontroly předvolby "+420". Příklad jsem zkoušela vyřešit ještě před přidáním Jirkovy aktualizace, kde popisuje, jak předvolbu zkontrolovat. Dělala jsem to pomocí indexů, ale měla jsem tam podmínku: if phoneNumber[0:3] == "+420". Předpokládala jsem, že když potřebuju první čtyři znaky, tak je to 0, 1, 2, 3. Pořád mi to nefungovalo a už jsem nevěděla co s tím :-D 
Následně jsem si všimla doplňku od Jirky, kde přesně píše, že musíme zadat:  cislo[0:4]. Tak jsem to udělala podle popisu a vše začalo fungovat. Ale není mi pořád moc jasné, proč je v závorce [0:4] ... :-)

**Comment by andywaltlova** [comment]
Ahoj 👋 ! 

Ohledne slicingu, me vzdy pomaha obrazek. Indexy si spis predstavuji jako oddelovace jednotlivych hodnot, potom mi dava vetsi smysl, ze je potreba vzdy zvolit o jedna vetsi index (ten co uz tam jakoby nechci mit) :)

```
 indexy:               0   1   2   3   4   5
 list hodnot           | + | 4 | 2 | 0 | 7 |
 indexy:              -6  -5  -4  -3  -2  -1
```
Kdyz chci prvni znak, tak jsme zvykli delat item[0], ale stejne by bylo udelat [0:1] nebo s vynechanim nuly [:1].
U druheho znaku pak [1] nebo [1:2] (tady uz nemuzu vynechat prvni cislo protoze bych dostala prvni dva znaky)
- Kdyz chci jeden znak, tak beru index jakoby predchazejici
- Kdyz chci interval tak beru od indexu predchazejici prvnimu prvku ktery chci az po index po poslednim prvku
- Plati to i u zapornych indexu, jen pozor na zaporna cisla, muze to byt matouci 
---

### 6. úkol ✔️ 
- Super, neni co dodat :-) 
### 7. úkol ✔️ 
- Take pekne 👍 
### 8. úkol 
- Funguje to, ale nektere casti by mohli byt napsane lepe :), proto pridavam komentar - vesmes jde o posouvani radku
```python
vysledek1 = verification(phoneNumber)
if vysledek1:
  sms = input("Zadejte text zprávy: ")
  import math  # tohle je spatne citelne, importy urcite davej uplne nahoru v souboru
  # Idealni struktura souboru je  1.importy -> 2.definice trid a funkci -> 3.kod ktery se opravdy vykonava / vola
  smsCount = math.ceil(len(sms) / 180)
  paidText = smsCount * 3

  # Takhle ta funkce  neprinasi zadnou novou cinnost, bud ji dej pryc a nech si vypocet jak mas,  nebo ten vypocet
  # presun do funkce, ktere predas jako argument sms. udela vypocet a vrati ti cislo (takto to bylo zamysleno)
  def totalPrice(paidText): 
    return paidText
```

---

Poprosim akorat malicko poupravit tu 8, staci az budes pridavat zbytek ukolu :)

**Comment by RenataTuronova** [comment]
@andywaltlova 

Ahoj Andy, 
děkuji za vysvětlení slicingu, skvělá pomůcka :)  
U příkladu č. 8 - jasně, chápu, omylem jsem jako argument funkce zadala to, co chci vrátit. Nahrála jsem opravenou verzi.

Ohledně posledních dvou příkladů z druhé lekce ... nad těmi jsem strávila celkem dlouho.
Příklad č. 10 jsem nahrála, ten jsem nějak vyřešila, snad i správně.
Nicméně příklad č. 9 - to je teda oříšek. Popravdě vůbec si nevím rady, jak se prokousat k výsledku. Nahrála jsem jej sem nevyřešený, jen s nějakým pokusem zpracování, abys viděla, jak jsem na to zkoušela přijít. Nevím ale, jak ten seznam slovníků zpracovat (rozdělit) pro jednotlivé studenty, abych je mohla použít jako argument funkce k hodnocení studenta. Můžeš mi prosím nějak poradit? Moc děkuji :)

**Comment by andywaltlova** [comment]
### 8 ✔️ 
- super, pekne upraveno 👍 
- dodam jen malickost: posledni radek, kde vypisujes cenu te sms, idealni by bylo mit ho take v podmince na radku 30-31, protoze tu cenu chces prece spocitat jen pokud sms opravdu odesilas (mas spravne telefoni cislo)
### 9
- ano, myslim ze tento ukol byl nejtezsi :)
-  Nejvetsi problem je tady v tom ze nam ve slovniku dela neporadek to jmeno, vsechny hodnoty jsou cisla, prave krome jmena - coz ti i pridelalo praci kvuli rozpoznani datoveho typu
- Jinak jsi ale na dobre ceste, popisu ti slovne kroky s napovedami, jak se idealne dobrat k vysledku: 
```py
for student in vysledky:
  # Nejvetsi problem je, ze nam tam prekazi ten jediny klic jmeno, ktery neni cislo (zaroven to jmeno potrebujeme jen k finalnimu vypisu)
  # 1. Pomoci funkce pop() si ho pro zjednoduseni pocitani vyhodime ze slovniku a ulozime do promene (vyhozena_hodnota = slovnik.pop(klic_k_vyhozeni))
  # 2. Pote bych zavolala funkci ohodnot_studenta(slovnik), ktere uz predas slovnik, kde jsou jen ty predmety a jejich znamky (po pouziti pop uz tam to jmeno neni)
  # 3. Ve funkci ohodnot_studenta() uz mas peknou podminku, jedine co chybi je vypocet prumeru (ktery uz mas napul hotovy) - pozor ze do podminek musis i zakomponovat jestli se treba v slovnik.values() nenachazi 5 (-> neprospel), a u vyznamenani skontrolovat nejen prumer ale i ze nema 3 ( 3 not in slovnik.values())
  # 4. Pro nejjednodusi vypocet prumeru muzes pouzit funkce sum() a len(). Diky tomu, ze ve slovniku uz jsou v hodnotach jen cisla, muzes pouzit sum(slovnik.values()), a funkci len(slovnik), ktera uz te samotnou napadla :)
  # 5. No a nakonci uz chybi jen vypis :) jmeno by si mela mit v promenne (kam sis ho ulozila pri pouziti pop) a retezec ti vrati volani funkce  ohodnot_studenta()
```
### 10 ✔️ 
- uznam ti to, jenom pozor na nekolik veci
    - paramtery `conference` a `newsletter` maji defaultni hodnotu typu `bool` (ze zadani), proto se ocekava ze i pri vyplneni toho argumentu, dostane opet `bool` hodnotu, predstav si ze proste pred volanim funkce se ten vstup od uzivatele nejak zpracuje a ta samotna funkce uz dostane jen bool hodnotu (aby to bylo konzistentni). Princip mas dobre, je to jen upozorneni, ze kdyz po tobe bude nekdo cizi kod cist, podle defaultni hodnoty argumentu bude cekat ze v nich opravdu jsou `bool` hodnoty.
```py
# pak by to vypadalo jen takto
# conference
  if conference:
    points += 1
# newsletter
  if newsletter:
    points += 1
```

- a pak jen malickost:
```py
# tento else nic nedela, nema vliv na body :) U konference a newsletteru taky preci nepricitas 0
else:
    points += 0
```

---

Skvela prace 👍 Pokud treba chces prozatim devitku vynechat, klidne se vrhni na ukoly z dalsiho tydne a k tomuto se pak muzes vratit :) 

Co jsem tak vypozorovala, tak kdyz uz nekdo odevzdal vse z druheho tydne, prisli jim pak dalsi dve lekce ( na objektove orientovane programovani ) jednodussi. Doporucovala bych udelat ten tyden 3 a 4 co nejdrive, aby jsi se pak mohla soustredit na pandas.

**Comment by RenataTuronova** [comment]
Super Andy, děkuji za komentáře k doladění příkladů :) a taky za nápovědy k úkolu č. 9, zkusím to brzy vyřešit, ale přesně jak píšeš, asi si od toho příkladu dám chvilku oddych, když to nevadí :D A hned jak s tou 9 pohnu, dám vědět.
Vím, že mám s úkoly trošku skluz..  Ale už jsem právě v mezičase vypracovala úkoly k 3. lekci, jen jsem je nechtěla odevzdávat před dořešením 2. lekce, aby to bylo postupně, nicméně na úkol č. 9 si tedy nechám trošku více času. Nahrála jsem už a vytvořila Issue s příklady k 3. lekci a dneska už právě řeším příklady ke 4. lekci.
Měj hezký den :)

**Comment by RenataTuronova** [comment]
@andywaltlova 

...  zapomněla jsem tě označit, aby sis zprávy všimla :)

**Comment by RenataTuronova** [comment]
@andywaltlova 

Ahoj Andy,

konečně jsem dořešila příklad č. 9 :D Prosím o kontrolu.

Děkuji :)

**Comment by andywaltlova** [comment]
Ahoj, super !
### 9. úkol ✔️ 
- Pekne napsane, elegantni a preledny kod :)
Jen pozor na `if max(marks) == 3:`, kdyby student mel napriklad 4 i 3, tak maximum je 4, ale stale ma tu trojku takze stale nema vyznamenani :)

Tyden 2 tedy uzavreny!
