### ISSUE TITLE
Hotové úkoly lekce č. 4 #4

### ISSUE THREAD

**Issue by RenataTuronova** [RenataTuronova/python-012021#4]
@andywaltlova 

Ahoj Andy,

prosím o zkontrolování příkladů ke 4. lekci :) 
U příkladů, kde byla jednodušší a složitější varianta, jsem vypracovala vždy obě možnosti. Akorát u příkladu č. 17 se mi nedaří složitější variantu vyřešit tak, aby vše fungovalo ... můžeš se na to prosím kouknout a napsat mi, co je špatně? 
Děkuji :)

**Comment by andywaltlova** [comment]
### 16 ✔️ 
- Pekne napsane 👍 
- Mozna bych v metodach `getInfo` vracela cely retezec, misto printovani toho z rodicovske tridy a vraceni dodatku u serialu/filmu - myslim pridat `super().getInfo()` taky do f-stringu. Nebo naopak vse dat jen do printu - takto mi prijde zvlastni ze cast se jen vypisuje a cast vraci, ale je to jen o preferencich :)
### 17
- U funkce ` addViews`  bylo mysleno ze rovnou zvysi uzivateluv atribut `self.lenghtOfWatching`. Zkratka se podival na film/serial, tak mu rovnou i zvysis ten atribut :) Takto to vzdy spocitas jen do promenne `result`, ktera slouzi jen k vypisu, ale uz si nemodifikujes samotny atribut objektu.

- Pokrocila varianta: Ano pekne, jenom male pripominky 
    - Do listu urcite musis pridavat cele objekty (ne jen jejich nazvy), protoze z nazvu nezjistit pak jejich delku 
    - Navic mas podobny problem jako v predchozi variante. Ve funkci `watchItem`, pridas spojeni polozek v listu a noveho itemu jen do obycejne promenne (ne primo do atributu `self.myList`), takze ten list shlednutych polozek se nezmeni. Vubec se neboj menit primo atributy tech objektu -> `self.myList += [newItem]` nebo `self.myList = self.myList + [newItem]`
    - ` lenghtOfWatching`, jdes na to dobre ! prochazet for cyklem chces urcite list tech polozek (`self.myList`). Radek 116 je navic moc odsazeny, takto to vzdy vrati delku pouze prvni polozky v `myList` :)
    
Pridavani polozek do listu je lepsi delat pomoci metody `append` -> `self.myList.append(polozka)` (misto pripojovani jednoprvkoveho seznamu), v tomto pripade to asi nicemu nevadi, akorat ta metoda append existuje presne proto aby si do listu mohla snadno pridavat polozky po jednom, spojovani listu se hodi spis kdyz mas dva delsi seznamy a chces je spojit.
### 18 
- Super, tady jen prosim uprav funkci ` saveRecord` 
    - bez ohledu na datum totiz vzdy zapis ulozis, a to ikdyz treba vratis retezec ze se jedna o chybne zadani -> zapis delas hned jako prvni v dane funkci (radek 29), idealne ho provest az kdyz mas datum zkonrolovany :)
    - zaroven pozor na to jak tvoris dnesni datum, tvuj kod se spoleha na to, ze mas nekde mimo tridu vytvorenou promennou `dateNow` (to neni uplne idealni -> vetsinou v kodu takove zavislosti nechces delat, protoze pak se hur hledaji chyby, vznikaji nedefinovane promenne), chci tim tedy rict ze bych vytvoren idnesniho data dala rovnou dovnitr  funkce, tim ti vznikne jeden funkci na nicem jinem nezavisly celek (funkce)  :)
### 19 ✔️ 
- Pekne 👍 
K zamysleni: opravdu potrebujes ten kod na radcich 24-35 duplikovat? (tri vpodstate totozne prikazy v kazde podmince) :) 
    - Napoveda ->  jedine co se ti vzdy meni je akorat argument ve volani funcke convert -> `converter.convert(promenna, "CZK", recquiredInTargetCyrrency)` 
   
### 20 ✔️ 
- Super 👍 
- Koukam, ze ten faker nema moc naucena slovenská jména - casto mi vypsal spis nejaka anglicka jmena :)

---
U 17 staci upravit zakladni variantu, tak aby se v metode `addViews` spravne zvysoval `self.lenghtOfWatching`
U 18 upravit `saveRecord`, aby se v pripade spatneho datumu zapis opravdu neulozil

Celkove ale skvela prace! Jen tak dal :-)

**Comment by RenataTuronova** [comment]
@andywaltlova 

Děkuji za připomínky k úkolům, Andy :)  Jednotlivé příklady jsem si u sebe v PyCharmu podle tvých tipů na vyladění poupravila a je fakt, že to tak vždy dává větší smysl. 
Příklad č. 17 a č. 18 jsem se snažila opravit, jak jsi mi napsala ...  nyní to funguje snad jak by mělo. Nahrála jsem to sem, tak uvidím, co mi k tomu napíšeš :)

Měj hezký večer :)

**Comment by andywaltlova** [comment]
### 17 ✔️ 
- Zakladni varianta super
- K rozsirene jen par poznamek
    - Pozor na pouziti prazdneho listu jako defaultniho u atributu funkce, popis problemu napriklad [tady](https://nikos7am.com/posts/mutable-default-arguments/). Je to jedna z mala veci, ktera neni uplne intuitivni v Pythonu.
    - radky 117 a 118, nestacilo by spocitat hodiny a minuty az po for cyklu misto v kazdem pruchodu? :) Je to jen malickost, ale u slozitejsich vypoctu / velkych poctu dat, by se to mohlo casovne prodrazit.

### 18 ✔️ 
- Super, skvela oprava 👍 

---
Jinak moc chvalim praci s gitem - pridavas jednotlive zmeny do logicky oddelenych a pojmenovanych commitu, tim ze mi je navic priradis i k issue se mi snaze kontroluje co si zmenila :)
