### ISSUE TITLE
Hotové úkoly lekce č.5

### ISSUE THREAD

**Issue by RenataTuronova** [RenataTuronova/python-012021#5]
@andywaltlova 

Ahoj Andy,

nahrála jsem hotové úkoly k 5. lekci, prosím o jejich zkontrolování. 
Děkuji :)

**Comment by andywaltlova** [comment]
### 21 ✔️ 
- Parada, neni co dodat 👍 
### 22 ✔️ 
- Take bez problemu
### 23 ✔️ 
- Super, i doplněk skvěle :-)
### 24 ✔️ 
- Take pěkné 👍 
### 25 ✔️ 
- Super, možná jen dodám, ohledne toho ukládání do nového dataframu, už si to vlastně měla v novem dataframu na řadku 19 (promenna `us`), pak jsis to znovu ulozila se stejnymi sloupci a hodnotami opet do nove promenne - uz zbytecne :) 

---
Jinak to byla radost opravovat, je videt, ze dotazovan ia filtrovani tabulek v pandasu ti nedela zadne problemy :)
Tyden 5 tedy hotov 🥳
