### ISSUE TITLE
Vypracovaný projekt k lekci č. 8 (Django)

### ISSUE THREAD

**Issue by RenataTuronova** [RenataTuronova/python-012021#8]
@andywaltlova

Hezký večer Andy,

přidala jsem na GitHub hotové úkoly (tedy projekt) k lekci č. 8. Snad se mi to povedlo správně nahrát, aby tam bylo vše :) Prosím o zkontrolování.

Děkuji, měj se pěkně :)

**Comment by andywaltlova** [comment]
Ahoj ! 

Ano povedlo, vidím vše a vše funguje tak jak má 👍 
Ké kódu také nemám žádne připomínky, pěkně sis poupravila tu úvodní stránku :)

✔️ 5b
