### ISSUE TITLE
Vypracovaný projekt Půjčovna(car_hire) k lekci č. 9

### ISSUE THREAD

**Issue by RenataTuronova** [RenataTuronova/python-012021#9]
@andywaltlova

Ahoj Andy,

nahrála jsem hotový projekt k 9. lekci. Přepsala jsem si názvy do angličtiny, protože používám běžně anglickou klávesnici, a je otrava každou chvilku přepínat na českou.

Prosím o zkontrolování úkolu. Děkuji :)

Hezký sobotní večer :)

**Comment by RenataTuronova** [comment]
Měla jsem problém s nahráním souboru po změně názvů do angličtiny, konkrétně soubor apps.py, který se poprvé nenahrál s přepsanými názvy, proto jsem ho poslala již opravený znovu :)

**Comment by andywaltlova** [comment]
Ahoj 👋 

- anglickym nazvum fandim, taky me nebavi prepinat klavesnice :) -> **pozor ale pak na soubor `catalog/views.py`**, kde ti to ted vraci html se spatnym odkazem na seznam aut, je tam jeste cesky text
- v souboru `car_hire/urls.py` mas **navic** jednu url adresu, konkretne tu posledni `catalog/list`. Ten konec `list` pridavas spravne az v `catalog.urls.py`. Tim ze ho mas i v  `car_hire/urls.py` , funguje ti naprikald i adresa http://127.0.0.1:8000/catalog/list/list/ 
- Jinak to vsechno funguje spravne, v databazi zaznamy take vidim :-)

✔️ 5b
